### ISSUE TITLE
Port maps are removed when kubernetes sends service updates

### ISSUE THREAD

**Issue by stewild** [rancher-sandbox/rancher-desktop-agent#32]
If Kubernetes sends updates for services and the port mapping has not changed, the existing maps are deleted anyway.

The events are handled by the [servicewatcher](https://github.com/rancher-sandbox/rancher-desktop-agent/blob/main/pkg/kube/servicewatcher.go) and in case of an update, changes for added and deleted port maps are collected. 
If nothing changes the lists for added and deleted port maps are empty and an event is sent to the `watcher`. The `watcher` calls `Add` and `Remove` on the PortTracker and just forwards the lists of added port maps. As the `Add` function is actually a replace, all port maps get removed.

**Comment by yevon** [comment]
Is there any release date for 1.9? This is causing lots of related issues with port bindings. Thanks!
